### ISSUE TITLE
error al intentar visualizar facturas!

### ISSUE THREAD

**Issue by fcgonzalez** [ProyectoAconcagua/l10n_ar_point_of_sale_v7#9]
Estimados soy nuevo en esto de Odoo, les comento es una instalacion sobre windows 8.1, con localizacion Argentina de proyecto aconcagua, intente instalar factura electronica me dio error.
Luego de esto no puedo visualizar mas las facturas emitidas el codigo de error es el siguiente:

Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\http.py", line 537, in _handle_exception
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\http.py", line 574, in dispatch
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\http.py", line 310, in _call_function
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\http.py", line 307, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\http.py", line 803, in __call__
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\http.py", line 403, in response_wrap
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server\openerp\addons\web\controllers\main.py", line 948, in call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server\openerp\addons\web\controllers\main.py", line 940, in _call_kw
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\service\model.py", line 113, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server\openerp\addons\web\controllers\main.py", line 939, in checked_call
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\models.py", line 3143, in read
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\api.py", line 239, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\models.py", line 3178, in read
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\api.py", line 239, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\models.py", line 3357, in _read_from_database
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\osv\fields.py", line 1464, in get
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server\openerp\addons\portal_sale\portal_sale.py", line 91, in <lambda>
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server\openerp\addons\portal_sale\portal_sale.py", line 104, in _portal_payment_block
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server\openerp\addons\payment\models\payment_acquirer.py", line 299, in render_payment_block
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server\openerp\addons\payment\models\payment_acquirer.py", line 271, in render
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server\openerp\addons\website\models\ir_ui_view.py", line 172, in render
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server\openerp\addons\base\ir\ir_ui_view.py", line 1017, in render
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server.\openerp\api.py", line 241, in wrapper
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server\openerp\addons\base\ir\ir_qweb.py", line 262, in render
  File "C:\Program Files (x86)\Odoo 8.0-20150913\server\openerp\addons\base\ir\ir_qweb.py", line 199, in get_template
QWebTemplateNotFound: Template u'account_payment.view_payment_line_tree' not found

gracias ! Facundo

**Comment by sebastiken** [comment]
@fcgonzalez te pido que comiences a utilizar los módulos de _Proyecto Aconcagua_ que están subidos a los repos de **OCA**. Podés acceder a los mismos desde [aquí](https://github.com/OCA/l10n-argentina). Están ambas versiones _7.0_ y _8.0_, una en cada rama.

Saludos.
